### ISSUE TITLE
LoIK: Benchmark pictures don't render

### ISSUE THREAD

**Issue by stephane-caron** [Simple-Robotics/simple-robotics.github.io#3]
Benchmark pictures on the [LoIK page](https://simple-robotics.github.io/publications/loik-solver/) don't render and have empty captions.

![image](https://github.com/user-attachments/assets/aa99db8d-ee8e-4f22-b76c-d10b947bf1c8)

@bwingo47 could you take a look at this?

**Comment by bwingo47** [comment]
Figures are now fixed, still need to upload the video to Youtube, or @stephane-caron have you already done that?

**Comment by stephane-caron** [comment]
Figures are fixed and the [video](https://www.youtube.com/watch?v=l4SlixZTZkk&t=4s) plays alright :+1: (I had not uploaded the video anywhere else.) Thanks @bwingo47, let's close this.
